# media.jackett.values.yml
replicaCount: 1

image:
  repository: "skalle/jackettvpn" # Special image to use Jackett over a VPN

env:
  - name: VPN_ENABLED
    value: "yes" # Enable Jackett over VPN
  - name: VPN_USERNAME
    valueFrom:
      secretKeyRef: # Reference to the secret | openvpn.username
        name: "openvpn"
        key: "username"
  - name: VPN_PASSWORD
    valueFrom:
      secretKeyRef: # Reference to the secret | openvpn.password
        name: "openvpn"
        key: "password"
  - name: LAN_NETWORK
    value: "192.168.1.0/24"
  - name: CREATE_TUN_DEVICE
    value: "true" # Needed for VPN
  - name: PUID
    value: "1000006"
  - name: PGID
    value: "1000004"

service:
  type: ClusterIP
  port: 80

volumes:
  - name: "media"
    persistentVolumeClaim:
      claimName: "media" # PersistentVolumeClaim created earlier
  - name: "dev-tun"  # Needed for VPN
    hostPath:
      path: "/dev/net/tun"
  - name: config
    persistentVolumeClaim:
      claimName: "config" # PersistentVolumeClaim created earlier

volumeMounts:
  - name: "config"
    mountPath: "/config"
    subPath: "jackett" # Path /mnt/ssd/media/configs/jackett where jackett writes the configuration
  - name: "media"
    mountPath: "/downloads"
    # subPath: "downloads/jackett" # Path /mnt/ssd/media/downloads/jackett ???

securityContext:
  capabilities: # Needed for VPN
    add:
      - NET_ADMIN
