apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  nfs:
    path: /volume2/k8s/jellyfin-config
    server: store
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
