---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-config-pv
spec:
  storageClassName: manual-config
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  nfs:
    path: /volume2/k8s/configs
    server: store
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
