persistentVolumeClaim:
  enabled: true

serviceTCP:
  loadBalancerIP: 192.168.1.241
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer

serviceUDP:
  loadBalancerIP: 192.168.1.241
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
