## media.sonarr.values.yml
replicaCount: 1

env:
  - name: PUID
    value: "1000006"
  - name: PGID
    value: "1000004"

service:
  type: ClusterIP
  port: 80

volumes:
  - name: media-ssd
    persistentVolumeClaim:
      claimName: "media-ssd" # PersistentVolumeClaim created earlier

volumeMounts:
  - name: media-config
    mountPath: "/config"
    subPath: "sonarr" # Path /mnt/ssd/media/configs/sonarr where sonarr writes the configuration
  - name: manual-media
    mountPath: "/downloads/"
    #subPath: "downloads/transmission" # Path /mnt/ssd/media/downloads/transmission where sonarr picks up downloaded episodes
  - name: manual-media
    mountPath: "/tv"
    #subPath: "library/tv" # Path /mnt/ssd/media/library/tv where sonarr moves and renames the episodes
